# Generated by Django 5.2.7 on 2025-11-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalog/previews/",
                verbose_name="Превью",
            ),
        ),
    ]
